### ISSUE TITLE
Minor frontend updates

### ISSUE THREAD

**Issue by riddick-oe** [factryflow/factryflow#152]
- Remove help and support sidebar menu item
- Hide "Operator view"
- Move data type and user management to under settings sidebar menu
- Convert custom field datetime type fields into human readable format
- Add unique icons for all sidebar menu according to their names

**Comment by mrAvi07** [comment]
## Data Type: 
we should keep ```data type``` as it is in the sidebar menu since it's related to ```Job, Task, custom fields``` etc (models related to the application) and in the ```settings``` we could have only links that are related to account ( just like, personal details, scheduler related settings and user management)

**Comment by loststoner** [comment]
## Data Type: 
we should keep ```data type``` as it is in the sidebar menu since it's related to ```Job, Task, custom fields``` etc (models related to the application) and in the ```settings``` we could have only links that are related to account ( just like, personal details, scheduler related settings and user management)

**Comment by loststoner** [comment]
### PR link: https://github.com/factryflow/factryflow/pull/156
