### ISSUE TITLE
Add Custom Field Feature

### ISSUE THREAD

**Issue by loststoner** [factryflow/factryflow#64]
Issue Description:
---
**Overview:**
We want to let users create their own fields for any part of the app. This means they can add extra information that's important to them.

**Details:**
- Users can add their own fields to any part of the factryflow application.
- They can store different types of information for resources, task and other database model using custom field.
- custom field will be store in the custom field model itself.
- We'll create a new field in the Base Model called custom_field to hold all the custom fields together. It will be a json field.
- we will store only the name and value of custom field in the custom_field entity as a json field in the database.

**Steps:**
1. Add a custom_field entity in the base model.
2. Update the form and custom crud views and all services as per new entity in the database.
3. Update the app's interface so users can add and manage custom fields.
4. Update the test cases for custom fields.

**Benefits:**
- Users can personalize the app to fit their needs.
- Data will be better organized.
- Using the factryflow will be more efficient.

**Comment by Yacobolo** [comment]
Custom fields needs a schema so data can be validated. To have this we need a model which stores the information: generic model, field ID, field display name, field type. Everytime the custom_fields json field is updated it will be validated based on the schema. All fields should be optional.
